name: data-151-demo
channels:
    - conda-forge
    - pyviz
    - nodefaults
dependencies:
    - numpy
    - xarray
    - matplotlib
    - cartopy
    - dask
    - pooch
    - dask-gateway
    - jupyter
    - jupyterlab
    - netCDF4
    - hvplot
    - holoviews
    - geoviews
